### ISSUE TITLE
Create widget buttons

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1225]
Add widget buttons (to `SpartanWidgetHandler`). The buttons should support `WidgetOperation`s as listeners, i.e. mouse down/up, double click and mouse hold (on hold once per X ms). Image included in `WidgetOperation`.

**Comment by NivShalmon** [comment]
Due to #1310 I couldn't run the widget or test it since friday night. Thanks to @OriRoth's hard work I can now run the plugin again and so I can finally commit my work from friday and keep on working. This does mean I probably won't finish this this weak, since I lost most of it to technical issues.

So far, I've drawn the buttons and added basic listeners to them. Mostly playing with geometry and making sure everything looks good. Next is writing the listeners properly and making sure they work properly, creating the WidgetContext and finally picking the widgetOperations based on the preferenceStore (related to #1224).
Also, right now the amount of buttons is static, and they are drawn even if no widgetOperation is supplied. Not drawing a button with no widget operation would be easy, but making the amount of buttons configurable will require a while longer.

**Comment by NivShalmon** [comment]
The widget is now properly working, with all listeners tested and the WidgetContext being created properly. The remaining work (using the user configured operations) will be done in #1321

**Comment by OriRoth** [comment]
Great job! 🎉 🎉 🎉 
Excellent SWT technique.
