### ISSUE TITLE
Organize miscellaneous files

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1302]
We want to clean the first page from useless entries

**Comment by OriRoth** [comment]
`lib` is not the right place. I've created a directory named `plugin` and moved some plugin-related stuff there (and deleted others). We may move some other stuff into a `miscellaneous` directory, then `plugin` can be moved there as well.

**Comment by OriRoth** [comment]
Also, this is not a useless entry! It contained the plugin launch configuration. You can right click it -> run as -> spartan.plugin, and it should open a new eclipse with the plugin installed (as usual). After we're done with the meta-architectural change, this is going to be the way we would debug the plugin (and other stuff). Shared configuration instead of per-machine configurations!

**Comment by yossigil** [comment]
I thought so, but then I noticed you mentioned it in some tutorial. do you remember this?

**Comment by OriRoth** [comment]
No... there is this issue though #1284. Also I may have destroyed this configuration in some way, because the new versions of the PDE plugins cause troubles... so I cannot guarantee it will work properly on your machine.

**Comment by OriRoth** [comment]
@RoeiRaz also all gradle files- as much as possible.

**Comment by yossigil** [comment]
@RoeiRaz

**Comment by yossigil** [comment]
@OriRoth Is this done?

**Comment by OriRoth** [comment]
Pretty much. Looks fine to me.
