### ISSUE TITLE
fix bug for spartanizer shortcut ctrl+alt+-

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1330]
doesn't work on mac
might not work on linux

**Comment by yuvalsimon** [comment]
I need to a mac computer to check it, but currently you can use also `Ctrl+Alt+1` to spartanize and `Ctrl+Alt+2` to athenize

**Comment by yuvalsimon** [comment]
@ravivos check now if it works. I changed the shortcut to use only _Ctrl_ instead of _Ctrl+Alt_ as @dormaayan asked. In my computer the eclipse uses the shortcut _Ctrl + +/-_ to change the font size of the code and it is configured in this eclipse version (I didn't download any plugin for this), so I can't use this shortcuts. Ask the client if it works for him Raviv. Also I added _Ctrl + Alt + [/]_ as shortcuts for now
