### ISSUE TITLE
Add our own icons/images

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1331]

**Comment by ravivos** [comment]
@OriRoth, can you change the main picture to @yosefraisman's picture and tell us how hard is it so we can know if it is possible to generate our own pictures for some of the operations which we didn't find an appropriate pic for (s.a the clean project op)

**Comment by OriRoth** [comment]
Done. The fix was to add pictures directory to binary output in *build.properties*. In order to use a picture just put it under *plugin/pictures/* and call it with URL *plugin/pictures/<picture name>*.
You can set the background transparent by converting to *png* format then doing [this](https://stackoverflow.com/questions/12945763/how-to-convert-the-background-to-transparent).

**Comment by OriRoth** [comment]
@ravivos @yuvalsimon @tomerdragucki FYI
