### ISSUE TITLE
Move configuration dialog result of String[][] to Map<String,String>

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1415]
Move configuration dialog result of String[][] to Map<String,String> as needed for the widgetOperationEntery

Because now it is a String[][] which is only partially correct.
It is also partially related to #1321

**Comment by NivShalmon** [comment]
instead of using Map, it may be better to simply use ConfigurationMap and have Entry save a ConfigurationMap as well.

**Comment by ravivos** [comment]
The configuration is not a hashmap, it is a String[][].
I think our entry is fine and we should focus on changing this

**Comment by NivShalmon** [comment]
isn't this issue about changing the configuration from a String[][] to a Map? It's absurd to keep using String[][] now, and not typesafe. ConfigurationsMap is the object that represents a configuration of a widget, why should the Entry or preferences page represent it otherwise?

**Comment by ravivos** [comment]
coding done.
Still need to check edge cases s.a:
- [ ] entering empty results
- [ ] checking updated results confirmed
- [ ] updating configuration name + ops instantly

**Comment by OriRoth** [comment]
Why map string string? I think we can do better... at least define some
constantas for types. What about lists?

**Comment by ravivos** [comment]
well, there is a configurationMap object which @NivShalmon wrote, but the transfer from map to Configuration is already done automatically according to configuration (String[][]), So it's fine to leave it map from String to String over here

**Comment by NivShalmon** [comment]
While using Map<String,String> and changing that to confMap is currently possible, it is a somewhat weird choice to use that over a configuration map. I belive we were wrong at first when we wanted to store a map and agree with @OriRoth here.
Also, if this isn't released in this version anyways, we really have no reason not to do this the best way we can, such as use configurationMap instead of a simple Map<String,String>.
