### ISSUE TITLE
Spartanize button in menu is not clear

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1472]
It's not clear what this button does to it's description should be changed.
Also, It seems like it does not work properly.

We should make it loop over all tippers until the file is all spartanized and there are no more tippers available.

**Comment by RoeyMaor** [comment]
the user now has an option to "step" through the tipping process by choosing either single or recursive spartanization: 
![screenshot from 2017-06-13 22-05-17](https://user-images.githubusercontent.com/16507852/27099859-e75651d0-5084-11e7-99a4-361db2439629.png)

![screenshot from 2017-06-13 22-05-30](https://user-images.githubusercontent.com/16507852/27099867-eb27f750-5084-11e7-85cb-c48f5f4148ad.png)

**Comment by RoeyMaor** [comment]
will leave open for now, in order to add a button to switch the output to the input - allowing the user to "step" through single layers of tipping.

**Comment by RoeyMaor** [comment]
well, i thought this was about the spartanize button in the playground. it's about the one in the main menu. will split the discussion

**Comment by RoeyMaor** [comment]
It's not that it doesn't work properly, the problems are because the leonidas version of rename to cent causes an inifinite loop of tipping (which oddly doesnt throw any exception), which is ok considering it is marked as "under construction" by michal. this causes the file to be only partially spartanized or not at all.
also, fluentSetter causes an exception.

removing these two tippers via toolbox controller solves the issues with this button

will just rename the button and close
