### ISSUE TITLE
A Mechanism to create PSI trees from arbitrary code - and retrieve relevant subtree

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1478]
such arbitrary code can include, but not limited to:
- code that can be wrapped in a class
- code that can be wrapped in a method
- expression (can be wrapped in function call)
- enum-bound

**Comment by OriRoth** [comment]
We implemented this in the Eclipse plugin, you may take a look.

**Comment by michalcohen** [comment]
Anna used this kind of mechanism in the "Playground", as we talked in the last meeting. You can use this as well. @RoeyMaor

**Comment by RoeyMaor** [comment]
That doesn't work for all cases. also I want to create something that will be used both by the tests and the playground

**Comment by RoeyMaor** [comment]
Extracting the string of the relevant subtree like in the playground is insufficient, since in the tests we want to compare contents of trees. The issue is that such one-subtree-to-include-them-all doesn't always exist, and in some cases cannot be even artificially created (for example by wrapping in a block {} ).
The solution i'm considering now is still using strings, but in a canonical form (single spaces, newlines), this approach has it's own issues but i think it is less cumbersome than the one-subtree-to-include-them-all approach

**Comment by michalcohen** [comment]
If I understand, what Anna did isn't "one-subtree-to-include-them-all " rather "lets try one of this very limited list of encapsulating trees possible":
- Try not wrapping the code. Are there errors?
- Try wrapping with class. Are there errors?
- Try wrapping with method declaration. Are there errors?
- Try wrapping with method call expression.
If there are still errors, they are probably since the user entered errors himself.
Is that what you mean? In which cases it doesn't work in the tests?

**Comment by RoeyMaor** [comment]
i didnt say what she did was one-subtree-to-include-them-all. she used strings, but when i want to compare two trees that represent the same code (perhaps with minute differences like indentation) i can't rely on that string output
