### ISSUE TITLE
No examples for tippers

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Main#1598]
In the preferences window where we can choose tippers it says to double click for an example but almost all tipper don't have any example.

**Comment by NivShalmon** [comment]
@ArthurSap The tippers are part of the spartanizer, and not part of our project. Since the examples are a new mechanic we added, most tippers don't have them yet. Since we only do maintainance work on the spartanizer, we didn't have the time to go over every single tipper and add examples to all of them.
I'm putting this is the backlog for now

**Comment by ArthurSap** [comment]
I don't really know to which project it belongs but since the athenizer does make use of the tippers (in the shrinking) I thought it was related.

**Comment by OriRoth** [comment]
Known.
