### ISSUE TITLE
Remove package plugin.old

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#917]
@M4tt30rru : you have some classes that depend on this. We need your help here. Ori will probably tell you what to do.

**Comment by M4tt30rru** [comment]
The dependencies are with LaconizeProject which depends on SingleTipper (in plugin.old) and Application (that is the class implementing a command line client at the beginnig) in cmdline package. 
If we want to preserve the functionalities of Application we can temporarly move these classes in LaconizeProject and SingleTipper to cmdline package. However, if we move SingleTipper we should move also QuickFixer (because the former is referenced in the latter). Maybe the easiest solution is to remove Application that it is not used anymore. In any case I am waiting for @OriRoth feedback.

**Comment by OriRoth** [comment]
I do not think we are ready to get rid of `plugin.old`. Some work should be done in order to replace some of the old implementations.
@M4tt30rru notice the classes in `plugin.old` are divided into classes in use by `plugin`, and classes in use by `cmd`. If you want to remove `plugin.old` you should transfer each class to the package that uses it. I'll try to summarize (check it):
* `BaseHandler` - cmd
* `eclipse` - plugin
* `LaconizeCurrent` - cmd/delete
* `LaconizeProject` - cmd
* `LaconizeSelection` - cmd/delete
* `QuickFixer` - delete
* `Refactorer` - delete
* `RefactorerUtil` - delete
* `RefreshAll` - plugin
* `SingleTipper` - plugin
* `SingleTipperApplicator` - ??? (probably delete)
* `SpartanizableAll` - plugin (actually I'll try to delete this now)

**Comment by OriRoth** [comment]
I did some work... `SingleTipper` and `SingleTipperApplicator` are in use by `plugin` and should be replaced ASAP.
